--Factions--

--Factions Non-Impériales--

Chaos = FactionInfo():setName("Chaos")
Chaos:setGMColor(255, 0, 0)
Chaos:setDescription([[Vaisseau ou appareil portant les identifiants corrompus des serviteurs du Chaos. Le Chaos est une force sournoise et vile qui n'a de cesse de s'opposer à l'Imperium depuis des temps immémoriaux. Ses serviteurs tentent continuellement de saper l'autorité Impériale, d'encourager la piraterie et la dissention en son sein afin de provoquer la chute de l'Humanité. Les vaisseaux et les hérétiques portant la marque de l'Archi-ennemi doivent être détruits où qu'ils se trouvent.]])

Epave = FactionInfo():setName("Epave")
Epave:setGMColor(167, 167, 167)
Epave:setDescription([[Vaisseau ou appareil émettant des appels de détresse en continu.]])

Neutre = FactionInfo():setName("Neutre")
Neutre:setGMColor(255, 255, 255)
Neutre:setDescription([[Cet objet n'émet aucune signature d'affiliation.]])

Xenos = FactionInfo():setName("Xenos")
Xenos:setGMColor(255, 0, 128)
Xenos:setDescription([[Vaisseau ou appareil émettant des signatures cohérentes mais non-humaines, sans doute des Xenos. Le terme "Xeno" regroupe toute éspèce non-humaine, qu'elle soit intelligente ou non, vivante ou éteinte, et dans un contexte spatial, tout objet identifié comme tel doit n'être approché qu'avec prudence.

Il est rappelé que le contact et la mise en place de négociations ou d'accords avec les Xenos est strictement interdit à toute personne non-habilitée, et que la sentance pour les contrevenants est la mort, sans distinction de grade ou de fonction.]])

Tau = FactionInfo():setName("T'au")
Tau:setGMColor(255, 128, 0)
Tau:setDescription([[Vaisseau ou appareil émettant les signatures typiques des Xenos T'au. Les T'au sont une éspèce jeune et dynamique dont l'expansion rapide dans ce secteur de la galaxie se fait au détriment de l'Imperium. Quand les T'au furent identifiés comme menace spatiale pour la première fois, plusieurs mondes Impériaux les avaient déjà rejoints, convaincus par leurs promesses de prospérité et leur concept de "Bien Suprème". Ouverts à la diplomatie, ils n'hésitent pas à en user et en abuser pour parvenir à leurs fins.]])

Eldar = FactionInfo():setName("Eldar")
Eldar:setGMColor(0, 255, 255)
Eldar:setDescription([[Vaisseau ou appareil émettant les signatures typiques des Xenos Eldars. Les Eldars sont une éspèce de Xenos sournoise et vile, un peuple amoindri qui n'a pas la descence de s'éteindre avec dignité et qui use de tromperie, fausses alliances et trahisons pour vaincre ses ennemis. Nombre de Capitaines qui ont vu des forces Eldars combattre à leurs côtés ont été trahis par ces mêmes forces peu de temps après, avant de les voir revenir, porteurs de promesses d'alliance, pour combattre une menace commune. Aussi changeants que les vents solaires sur lesquels leurs vaisseaux voguent, il ne faut leur faire confiance sous aucun prétexte.]])

Federation = FactionInfo():setName("Fédération")
Federation:setGMColor(0, 128, 250)
Federation:setDescription([[Vaisseau ou appareil émettant des codes de type Impérial, mais non reconnus et n'étant pas enregistré auprès des forteresses du Segmentum.]])

--Faction Impériales--
--(Les factions ont été placées de manière à faciliter leur accès depuis le jeu)--

Gambit = FactionInfo():setName("Gambit Metallicus")
Gambit:setGMColor(255, 255, 0)
Gambit:setDescription([[Vaisseau ou appareil rattaché au Gambit Métallicus, Croiseur de calsse Lunar de l'Adeptus Mechanicus commandé par le Magos Explorator Quintus Davianos 13.2.]])

Defiance = FactionInfo():setName("Défiance")
Defiance:setGMColor(255, 255, 0)
Defiance:setDescription([[Vaisseau ou appareil rattaché au Défiance, propriété du Seigneur-Capitaine Vargas Anomtarkus.

Libre-Marchand issu de la lignée Anomtarkus de Tarkus V, le Seigneur-Capitaine Vargas Anomtarkus s'est récemment fait connaitre à la fois pour la redécouverte du Grand-Croiseur de classe Repulsive de son ancètre, ses actions audacieuses voir téméraires, tant dans le vide qu'au sol, mais également pour son parcourt qui l'a plusieurs fois conduit devant les tribunaux Impériaux.

Si des accusations d'incompétence, d'hérésie et de technohérésie ont été portées contre lui, nottament par le Magos Explorator Quintus Davianos 13.2, il semble que la seule peine retenue à son encontre soit une croisade de pénitence accomplie avec succès et une mise sous la surveillance de l'Ecclésiarchie.]])

Marine = FactionInfo():setName("Navi Imperialis")
Marine:setGMColor(24, 110, 21)
Marine:setDescription([[Si les Flottes Marchandes détiennent presque tous les vaisseaux de l'Impérium, la quasi-totalité des Croiseurs, Cuirassés et autres vaisseaux dédiés au combat spatial sont aux mains de la Marine Impériale, et appuyés de nombres de frégates, destroyers et autres vaisseaux plus modestes destinés à les escorter ou à apporter un soutien au sol ou dans les airs.

Contrairement à une idée largement répandue, la plupart des vaisseaux de la Marine sont des vaisseaux intrasystèmes, incapables de voyager par le Warp, et servent éssentiellement à défendre les planètes contre les petites invasions et les attaques de pirates. Cependant, les vaisseaux restant sont si formidablement puissants qu'ils suffisent à remettre au pas un monde au bord de la rébellion par leur simple arrivée dans un système, et sont capables d'apporter le juste courroux de l'Empereur jusqu'aux confins de la galaxie si il le faut.]])

Mercanti = FactionInfo():setName("Navi Mercanti")
Mercanti:setGMColor(24, 110, 21)
Mercanti:setDescription([[ Vaisseau ou appareil appartennant à la Flotte Marchande Impériale. Cette dernière regroupe plus de 90% des stations et vaisseaux Impériaux et les consacre au commerce. Les Capitaines de ces navires possèdent une Charte définissant les routes commerciales sur lesquelles ils sont autorisés à opérer ou non.

La valeur et la puissance de ces Chartes est déterminé non seulement par les routes qui y sont rattachées, mais également par leur mode de transmission. Si le possesseur d'une Charte Mercantile est attaché à une route bien spécifique et peut être révoqué et son vaisseau saisit sans grande peine, un Libre-Capitaine a au contraire l'interdiction d'opérer sur les routes commerciales établies, et doit désservir les planètes les plus éloignées.

De plus, un Capitaine peut également recevoir l'honneur très recherché de pouvoir choisir son propre successeur, en étant nommé Capitaine (ou Libre-Capitaine) Héritier. Il va sans dire que l'Imperium ne confie pas ses vaisseaux à n'importe qui, et la plupart des Capitaines et Libres-Capitaines sont issus des rangs de la Marine.]])

Mechanicus = FactionInfo():setName("Adeptus Mechanicus")
Mechanicus:setGMColor(255, 128, 0)
Mechanicus:setDescription([[Vaisseau ou appareil appartennant à l'Adeptus Mechanicus. L'Adeptus Mechanicus est l'une des rares organisations de l'Imperium à posséder ses propres vaisseaux. Si certains sont assez standards et peuvent être comparés aux vaisseaux de la Marine ou de la Flotte Marchande, beaucoup sont d'une classe toute particulière, des vaisseaux-usines chargées exploiter les ressources spatiales et de les transformer en cours de trajet aux gigantesques Arches Mechanicus conçues pour récupérer les épaves et réparer les vaisseaux endommagés..]])

Independant = FactionInfo():setName("Navire Indépendant")
Independant:setGMColor(24, 110, 21)
Independant:setDescription([[ Vaisseau ou appareil Impérial n'appartennant à aucune Flotte, mais étant la propriété d'un particulier. Ce dernier est sans doute d'une importance non-négligeable. En effet, rares sont les individus capables de s'acheter leur propre vaisseau, en dehors des riches guildes marchandes, des familles de Navigators ou des Gouverneurs influents. Quand à en posséder plusieurs, c'est le signe d'une puissance et d'une richesse à ne pas négliger.]])


ImperiumMisthos = FactionInfo():setName("Imperium Misthos")
ImperiumMisthos:setGMColor(24, 110, 21)
ImperiumMisthos:setDescription([[Vaisseau ou appareil Imperial évoluant dans le système Gisperion.]])

ImperiumAgmenos = FactionInfo():setName("Imperium Agmenos")
ImperiumAgmenos:setGMColor(24, 110, 21)
ImperiumAgmenos:setDescription([[Vaisseau ou appareil Imperial évoluant dans le système Agmenos.]])

ImperiumAcadia = FactionInfo():setName("Imperium Acadia")
ImperiumAcadia:setGMColor(24, 110, 21)
ImperiumAcadia:setDescription([[Vaisseau ou appareil Imperial évoluant dans le système Acadia.]])

ImperiumPurusca = FactionInfo():setName("Imperium Purusca")
ImperiumPurusca:setGMColor(24, 110, 21)
ImperiumPurusca:setDescription([[Vaisseau ou appareil Imperial évoluant dans le système Purusca.]])

ImperiumJuno = FactionInfo():setName("Imperium Juno")
ImperiumJuno:setGMColor(24, 110, 21)
ImperiumJuno:setDescription([[Vaisseau ou appareil Imperial évoluant dans le système Juno.]])

ImperiumMerinita = FactionInfo():setName("Imperium Merinita")
ImperiumMerinita:setGMColor(24, 110, 21)
ImperiumMerinita:setDescription([[Vaisseau ou appareil Imperial évoluant dans le système Merinita.]])

ImperiumTriticum = FactionInfo():setName("Imperium Triticum")
ImperiumTriticum:setGMColor(24, 110, 21)
ImperiumTriticum:setDescription([[Vaisseau ou appareil Imperial évoluant dans le système Triticum.]])

MechanicusLascarios = FactionInfo():setName("Adeptus Mechanicus Lascarios")
MechanicusLascarios:setGMColor(255, 128, 0)
MechanicusLascarios:setDescription([[Vaisseau ou appareil Imperial évoluant dans le système Lascarios.]])

ImperiumUltraSemptor = FactionInfo():setName("Imperium Ultra Semptor")
ImperiumUltraSemptor:setGMColor(24, 110, 21)
ImperiumUltraSemptor:setDescription([[Vaisseau ou appareil Imperial évoluant dans le système Ultra Semptor.]])

MechanicusFractarius = FactionInfo():setName("Adeptus Mechanicus Fractarius")
MechanicusFractarius:setGMColor(255, 128, 0)
MechanicusFractarius:setDescription([[Vaisseau ou appareil Imperial évoluant dans le système Fractarius.]])

ImperiumGisperion = FactionInfo():setName("Imperium Gisperion")
ImperiumGisperion:setGMColor(24, 110, 21)
ImperiumGisperion:setDescription([[Vaisseau ou appareil Imperial évoluant dans le système Gisperion.]])

ImperiumTarkus = FactionInfo():setName("Imperium Tarkus")
ImperiumTarkus:setGMColor(24, 110, 21)
ImperiumTarkus:setDescription([[Vaisseau ou appareil Imperial évoluant dans le système Tarkus.]])

Imperium = FactionInfo():setName("Imperium")
Imperium:setGMColor(24, 110, 21)
Imperium:setDescription([[Quand plusieurs vaisseaux Impériaux oeuvrent de concert, il est courant qu'ils accordent leurs auspex et autres informations afin de bénéficier d'un meilleur apperçu de la situation.]])

--Anciennes Factions--

--Helena = FactionInfo():setName("Martyr de Sainte Héléna")
--Helena:setGMColor(255, 255, 0)
--Helena:setDescription([[Vaisseau ou appareil rattaché au Martyr de Sainte Héléna, Croiseur de classe Gothic de la Marine Impériale commandé par le Capitaine Erwyn Caeditz.

--Construit à Kar Duniash durant la Guerre Gothique, le Martys de Sainte Héléna est un vaisseau relativement récent, bien qu'il ai participé à son lot de combats contre les forces Xenos locales ainsi que les Puissances de la Ruine. Récemment revenu victorieux de sa mission dans l'Amas de Tvasos avec le "Celestis Veritas", il est à nouveau déployé dans le secteur Argosien.]])

--Celestis = FactionInfo():setName("Celestis Veritas")
--Celestis:setGMColor(255, 255, 0)
--Celestis:setDescription([[Vaisseau ou appareil rattaché au Celestis Veritas, Croiseur de classe Lunar de la Marine Impériale commandé par le Capitaine Imriel Lux Morningstar.

--Initialement conçu il y a un peu plus d'un millénaire pour renforcer la flotte du Segmentum Ultima, il fut à son lancement immédiatement détaché dans le sous-secteur Argosien afin de servir de pivot dans la lutte contre la piraterie ork, poste qu'il occupa de longues années jusqu'a sa participation à la destruction de la base Korsaire de PX-87654.

--Le vaisseau connut par la suite une longue période d'inactivité inexpliquée avant de repartir en mission dans l'Amas de Tvasos où il s'illustra aux côtés du Croiseur Gothic "Martyr de Sainte Héléna".]])


-- Relations des factions--

--Imperium--

ImperiumTarkus:setFriendly(Imperium)
ImperiumGisperion:setFriendly(Imperium)
MechanicusFractarius:setFriendly(Imperium)
MechanicusLascarios:setFriendly(Imperium)
ImperiumUltraSemptor:setFriendly(Imperium)
ImperiumTriticum:setFriendly(Imperium)
ImperiumMerinita:setFriendly(Imperium)
ImperiumJuno:setFriendly(Imperium)
ImperiumPurusca:setFriendly(Imperium)
ImperiumAcadia:setFriendly(Imperium)
ImperiumAgmenos:setFriendly(Imperium)
ImperiumMisthos:setFriendly(Imperium)
Marine:setFriendly(Imperium)
Mercanti:setFriendly(Imperium)
Mechanicus:setFriendly(Imperium)
Independant:setFriendly(Imperium)
Defiance:setFriendly(Imperium)
Gambit:setFriendly(Imperium)

Imperium:setFriendly(ImperiumTarkus)
ImperiumGisperion:setFriendly(ImperiumTarkus)
MechanicusFractarius:setFriendly(ImperiumTarkus)
MechanicusLascarios:setFriendly(ImperiumTarkus)
ImperiumUltraSemptor:setFriendly(ImperiumTarkus)
ImperiumTriticum:setFriendly(ImperiumTarkus)
ImperiumMerinita:setFriendly(ImperiumTarkus)
ImperiumJuno:setFriendly(ImperiumTarkus)
ImperiumPurusca:setFriendly(ImperiumTarkus)
ImperiumAcadia:setFriendly(ImperiumTarkus)
ImperiumAgmenos:setFriendly(ImperiumTarkus)
ImperiumMisthos:setFriendly(ImperiumTarkus)
Marine:setFriendly(ImperiumTarkus)
Mercanti:setFriendly(ImperiumTarkus)
Mechanicus:setFriendly(ImperiumTarkus)
Independant:setFriendly(ImperiumTarkus)
Defiance:setFriendly(ImperiumTarkus)
Gambit:setFriendly(ImperiumTarkus)

Imperium:setFriendly(ImperiumGisperion)
ImperiumTarkus:setFriendly(ImperiumGisperion)
MechanicusFractarius:setFriendly(ImperiumGisperion)
MechanicusLascarios:setFriendly(ImperiumGisperion)
ImperiumUltraSemptor:setFriendly(ImperiumGisperion)
ImperiumTriticum:setFriendly(ImperiumGisperion)
ImperiumMerinita:setFriendly(ImperiumGisperion)
ImperiumJuno:setFriendly(ImperiumGisperion)
ImperiumPurusca:setFriendly(ImperiumGisperion)
ImperiumAcadia:setFriendly(ImperiumGisperion)
ImperiumAgmenos:setFriendly(ImperiumGisperion)
ImperiumMisthos:setFriendly(ImperiumGisperion)
Marine:setFriendly(ImperiumGisperion)
Mercanti:setFriendly(ImperiumGisperion)
Mechanicus:setFriendly(ImperiumGisperion)
Independant:setFriendly(ImperiumGisperion)
Defiance:setFriendly(ImperiumGisperion)
Gambit:setFriendly(ImperiumGisperion)

Imperium:setFriendly(MechanicusFractarius)
ImperiumTarkus:setFriendly(MechanicusFractarius)
ImperiumGisperion:setFriendly(MechanicusFractarius)
MechanicusLascarios:setFriendly(MechanicusFractarius)
ImperiumUltraSemptor:setFriendly(MechanicusFractarius)
ImperiumTriticum:setFriendly(MechanicusFractarius)
ImperiumMerinita:setFriendly(MechanicusFractarius)
ImperiumJuno:setFriendly(MechanicusFractarius)
ImperiumPurusca:setFriendly(MechanicusFractarius)
ImperiumAcadia:setFriendly(MechanicusFractarius)
ImperiumAgmenos:setFriendly(MechanicusFractarius)
ImperiumMisthos:setFriendly(MechanicusFractarius)
Marine:setFriendly(MechanicusFractarius)
Mercanti:setFriendly(MechanicusFractarius)
Mechanicus:setFriendly(MechanicusFractarius)
Independant:setFriendly(MechanicusFractarius)
Defiance:setFriendly(MechanicusFractarius)
Gambit:setFriendly(MechanicusFractarius)

Imperium:setFriendly(MechanicusLascarios)
ImperiumTarkus:setFriendly(MechanicusLascarios)
ImperiumGisperion:setFriendly(MechanicusLascarios)
MechanicusFractarius:setFriendly(MechanicusLascarios)
ImperiumUltraSemptor:setFriendly(MechanicusLascarios)
ImperiumTriticum:setFriendly(MechanicusLascarios)
ImperiumMerinita:setFriendly(MechanicusLascarios)
ImperiumJuno:setFriendly(MechanicusLascarios)
ImperiumPurusca:setFriendly(MechanicusLascarios)
ImperiumAcadia:setFriendly(MechanicusLascarios)
ImperiumAgmenos:setFriendly(MechanicusLascarios)
ImperiumMisthos:setFriendly(MechanicusLascarios)
Marine:setFriendly(MechanicusLascarios)
Mercanti:setFriendly(MechanicusLascarios)
Mechanicus:setFriendly(MechanicusLascarios)
Independant:setFriendly(MechanicusLascarios)
Defiance:setFriendly(MechanicusLascarios)
Gambit:setFriendly(MechanicusLascarios)

Imperium:setFriendly(ImperiumUltraSemptor)
ImperiumTarkus:setFriendly(ImperiumUltraSemptor)
ImperiumGisperion:setFriendly(ImperiumUltraSemptor)
MechanicusFractarius:setFriendly(ImperiumUltraSemptor)
MechanicusLascarios:setFriendly(ImperiumUltraSemptor)
ImperiumTriticum:setFriendly(ImperiumUltraSemptor)
ImperiumMerinita:setFriendly(ImperiumUltraSemptor)
ImperiumJuno:setFriendly(ImperiumUltraSemptor)
ImperiumPurusca:setFriendly(ImperiumUltraSemptor)
ImperiumAcadia:setFriendly(ImperiumUltraSemptor)
ImperiumAgmenos:setFriendly(ImperiumUltraSemptor)
ImperiumMisthos:setFriendly(ImperiumUltraSemptor)
Marine:setFriendly(ImperiumUltraSemptor)
Mercanti:setFriendly(ImperiumUltraSemptor)
Mechanicus:setFriendly(ImperiumUltraSemptor)
Independant:setFriendly(ImperiumUltraSemptor)
Defiance:setFriendly(ImperiumUltraSemptor)
Gambit:setFriendly(ImperiumUltraSemptor)

Imperium:setFriendly(ImperiumTriticum)
ImperiumTarkus:setFriendly(ImperiumTriticum)
ImperiumGisperion:setFriendly(ImperiumTriticum)
MechanicusFractarius:setFriendly(ImperiumTriticum)
MechanicusLascarios:setFriendly(ImperiumTriticum)
ImperiumUltraSemptor:setFriendly(ImperiumTriticum)
ImperiumMerinita:setFriendly(ImperiumTriticum)
ImperiumJuno:setFriendly(ImperiumTriticum)
ImperiumPurusca:setFriendly(ImperiumTriticum)
ImperiumAcadia:setFriendly(ImperiumTriticum)
ImperiumAgmenos:setFriendly(ImperiumTriticum)
ImperiumMisthos:setFriendly(ImperiumTriticum)
Marine:setFriendly(ImperiumTriticum)
Mercanti:setFriendly(ImperiumTriticum)
Mechanicus:setFriendly(ImperiumTriticum)
Independant:setFriendly(ImperiumTriticum)
Defiance:setFriendly(ImperiumTriticum)
Gambit:setFriendly(ImperiumTriticum)

Imperium:setFriendly(ImperiumMerinita)
ImperiumTarkus:setFriendly(ImperiumMerinita)
ImperiumGisperion:setFriendly(ImperiumMerinita)
MechanicusFractarius:setFriendly(ImperiumMerinita)
MechanicusLascarios:setFriendly(ImperiumMerinita)
ImperiumUltraSemptor:setFriendly(ImperiumMerinita)
ImperiumTriticum:setFriendly(ImperiumMerinita)
ImperiumJuno:setFriendly(ImperiumMerinita)
ImperiumPurusca:setFriendly(ImperiumMerinita)
ImperiumAcadia:setFriendly(ImperiumMerinita)
ImperiumAgmenos:setFriendly(ImperiumMerinita)
ImperiumMisthos:setFriendly(ImperiumMerinita)
Marine:setFriendly(ImperiumMerinita)
Mercanti:setFriendly(ImperiumMerinita)
Mechanicus:setFriendly(ImperiumMerinita)
Independant:setFriendly(ImperiumMerinita)
Defiance:setFriendly(ImperiumMerinita)
Gambit:setFriendly(ImperiumMerinita)

Imperium:setFriendly(ImperiumJuno)
ImperiumTarkus:setFriendly(ImperiumJuno)
ImperiumGisperion:setFriendly(ImperiumJuno)
MechanicusFractarius:setFriendly(ImperiumJuno)
MechanicusLascarios:setFriendly(ImperiumJuno)
ImperiumUltraSemptor:setFriendly(ImperiumJuno)
ImperiumTriticum:setFriendly(ImperiumJuno)
ImperiumMerinita:setFriendly(ImperiumJuno)
ImperiumPurusca:setFriendly(ImperiumJuno)
ImperiumAcadia:setFriendly(ImperiumJuno)
ImperiumAgmenos:setFriendly(ImperiumJuno)
ImperiumMisthos:setFriendly(ImperiumJuno)
Marine:setFriendly(ImperiumJuno)
Mercanti:setFriendly(ImperiumJuno)
Mechanicus:setFriendly(ImperiumJuno)
Independant:setFriendly(ImperiumJuno)
Defiance:setFriendly(ImperiumJuno)
Gambit:setFriendly(ImperiumJuno)

Imperium:setFriendly(ImperiumPurusca)
ImperiumTarkus:setFriendly(ImperiumPurusca)
ImperiumGisperion:setFriendly(ImperiumPurusca)
MechanicusFractarius:setFriendly(ImperiumPurusca)
MechanicusLascarios:setFriendly(ImperiumPurusca)
ImperiumUltraSemptor:setFriendly(ImperiumPurusca)
ImperiumTriticum:setFriendly(ImperiumPurusca)
ImperiumMerinita:setFriendly(ImperiumPurusca)
ImperiumJuno:setFriendly(ImperiumPurusca)
ImperiumAcadia:setFriendly(ImperiumPurusca)
ImperiumAgmenos:setFriendly(ImperiumPurusca)
ImperiumMisthos:setFriendly(ImperiumPurusca)
Marine:setFriendly(ImperiumPurusca)
Mercanti:setFriendly(ImperiumPurusca)
Mechanicus:setFriendly(ImperiumPurusca)
Independant:setFriendly(ImperiumPurusca)
Defiance:setFriendly(ImperiumPurusca)
Gambit:setFriendly(ImperiumPurusca)

Imperium:setFriendly(ImperiumAcadia)
ImperiumTarkus:setFriendly(ImperiumAcadia)
ImperiumGisperion:setFriendly(ImperiumAcadia)
MechanicusFractarius:setFriendly(ImperiumAcadia)
MechanicusLascarios:setFriendly(ImperiumAcadia)
ImperiumUltraSemptor:setFriendly(ImperiumAcadia)
ImperiumTriticum:setFriendly(ImperiumAcadia)
ImperiumMerinita:setFriendly(ImperiumAcadia)
ImperiumJuno:setFriendly(ImperiumAcadia)
ImperiumPurusca:setFriendly(ImperiumAcadia)
ImperiumAgmenos:setFriendly(ImperiumAcadia)
ImperiumMisthos:setFriendly(ImperiumAcadia)
Marine:setFriendly(ImperiumAcadia)
Mercanti:setFriendly(ImperiumAcadia)
Mechanicus:setFriendly(ImperiumAcadia)
Independant:setFriendly(ImperiumAcadia)
Defiance:setFriendly(ImperiumAcadia)
Gambit:setFriendly(ImperiumAcadia)

Imperium:setFriendly(ImperiumAgmenos)
ImperiumTarkus:setFriendly(ImperiumAgmenos)
ImperiumGisperion:setFriendly(ImperiumAgmenos)
MechanicusFractarius:setFriendly(ImperiumAgmenos)
MechanicusLascarios:setFriendly(ImperiumAgmenos)
ImperiumUltraSemptor:setFriendly(ImperiumAgmenos)
ImperiumTriticum:setFriendly(ImperiumAgmenos)
ImperiumMerinita:setFriendly(ImperiumAgmenos)
ImperiumJuno:setFriendly(ImperiumAgmenos)
ImperiumPurusca:setFriendly(ImperiumAgmenos)
ImperiumAcadia:setFriendly(ImperiumAgmenos)
ImperiumMisthos:setFriendly(ImperiumAgmenos)
Marine:setFriendly(ImperiumAgmenos)
Mercanti:setFriendly(ImperiumAgmenos)
Mechanicus:setFriendly(ImperiumAgmenos)
Independant:setFriendly(ImperiumAgmenos)
Defiance:setFriendly(ImperiumAgmenos)
Gambit:setFriendly(ImperiumAgmenos)

Imperium:setFriendly(ImperiumMisthos)
ImperiumTarkus:setFriendly(ImperiumMisthos)
ImperiumGisperion:setFriendly(ImperiumMisthos)
MechanicusFractarius:setFriendly(ImperiumMisthos)
MechanicusLascarios:setFriendly(ImperiumMisthos)
ImperiumUltraSemptor:setFriendly(ImperiumMisthos)
ImperiumTriticum:setFriendly(ImperiumMisthos)
ImperiumMerinita:setFriendly(ImperiumMisthos)
ImperiumJuno:setFriendly(ImperiumMisthos)
ImperiumPurusca:setFriendly(ImperiumMisthos)
ImperiumAcadia:setFriendly(ImperiumMisthos)
ImperiumAgmenos:setFriendly(ImperiumMisthos)
Marine:setFriendly(ImperiumMisthos)
Mercanti:setFriendly(ImperiumMisthos)
Mechanicus:setFriendly(ImperiumMisthos)
Independant:setFriendly(ImperiumMisthos)
Defiance:setFriendly(ImperiumMisthos)
Gambit:setFriendly(ImperiumMisthos)

Imperium:setFriendly(Marine)
ImperiumTarkus:setFriendly(Marine)
ImperiumGisperion:setFriendly(Marine)
MechanicusFractarius:setFriendly(Marine)
MechanicusLascarios:setFriendly(Marine)
ImperiumUltraSemptor:setFriendly(Marine)
ImperiumTriticum:setFriendly(Marine)
ImperiumMerinita:setFriendly(Marine)
ImperiumJuno:setFriendly(Marine)
ImperiumPurusca:setFriendly(Marine)
ImperiumAcadia:setFriendly(Marine)
ImperiumAgmenos:setFriendly(Marine)
ImperiumMisthos:setFriendly(Marine)
Mercanti:setFriendly(Marine)
Mechanicus:setFriendly(Marine)
Independant:setFriendly(Marine)
Defiance:setFriendly(Marine)
Gambit:setFriendly(Marine)

Imperium:setFriendly(Mercanti)
ImperiumTarkus:setFriendly(Mercanti)
ImperiumGisperion:setFriendly(Mercanti)
MechanicusFractarius:setFriendly(Mercanti)
MechanicusLascarios:setFriendly(Mercanti)
ImperiumUltraSemptor:setFriendly(Mercanti)
ImperiumTriticum:setFriendly(Mercanti)
ImperiumMerinita:setFriendly(Mercanti)
ImperiumJuno:setFriendly(Mercanti)
ImperiumPurusca:setFriendly(Mercanti)
ImperiumAcadia:setFriendly(Mercanti)
ImperiumAgmenos:setFriendly(Mercanti)
ImperiumMisthos:setFriendly(Mercanti)
Marine:setFriendly(Mercanti)
Mechanicus:setFriendly(Mercanti)
Independant:setFriendly(Mercanti)
Defiance:setFriendly(Mercanti)
Gambit:setFriendly(Mercanti)

Imperium:setFriendly(Mechanicus)
ImperiumTarkus:setFriendly(Mechanicus)
ImperiumGisperion:setFriendly(Mechanicus)
MechanicusFractarius:setFriendly(Mechanicus)
MechanicusLascarios:setFriendly(Mechanicus)
ImperiumUltraSemptor:setFriendly(Mechanicus)
ImperiumTriticum:setFriendly(Mechanicus)
ImperiumMerinita:setFriendly(Mechanicus)
ImperiumJuno:setFriendly(Mechanicus)
ImperiumPurusca:setFriendly(Mechanicus)
ImperiumAcadia:setFriendly(Mechanicus)
ImperiumAgmenos:setFriendly(Mechanicus)
ImperiumMisthos:setFriendly(Mechanicus)
Marine:setFriendly(Mechanicus)
Mercanti:setFriendly(Mechanicus)
Independant:setFriendly(Mechanicus)
Defiance:setFriendly(Mechanicus)
Gambit:setFriendly(Mechanicus)

Imperium:setFriendly(Independant)
ImperiumTarkus:setFriendly(Independant)
ImperiumGisperion:setFriendly(Independant)
MechanicusFractarius:setFriendly(Independant)
MechanicusLascarios:setFriendly(Independant)
ImperiumUltraSemptor:setFriendly(Independant)
ImperiumTriticum:setFriendly(Independant)
ImperiumMerinita:setFriendly(Independant)
ImperiumJuno:setFriendly(Independant)
ImperiumPurusca:setFriendly(Independant)
ImperiumAcadia:setFriendly(Independant)
ImperiumAgmenos:setFriendly(Independant)
ImperiumMisthos:setFriendly(Independant)
Marine:setFriendly(Independant)
Mercanti:setFriendly(Independant)
Mechanicus:setFriendly(Independant)
Defiance:setFriendly(Independant)
Gambit:setFriendly(Independant)

Imperium:setFriendly(Defiance)
ImperiumTarkus:setFriendly(Defiance)
ImperiumGisperion:setFriendly(Defiance)
MechanicusFractarius:setFriendly(Defiance)
MechanicusLascarios:setFriendly(Defiance)
ImperiumUltraSemptor:setFriendly(Defiance)
ImperiumTriticum:setFriendly(Defiance)
ImperiumMerinita:setFriendly(Defiance)
ImperiumJuno:setFriendly(Defiance)
ImperiumPurusca:setFriendly(Defiance)
ImperiumAcadia:setFriendly(Defiance)
ImperiumAgmenos:setFriendly(Defiance)
ImperiumMisthos:setFriendly(Defiance)
Marine:setFriendly(Defiance)
Mercanti:setFriendly(Defiance)
Mechanicus:setFriendly(Defiance)
Independant:setFriendly(Defiance)
Gambit:setFriendly(Defiance)

Imperium:setFriendly(Gambit)
ImperiumTarkus:setFriendly(Gambit)
ImperiumGisperion:setFriendly(Gambit)
MechanicusFractarius:setFriendly(Gambit)
MechanicusLascarios:setFriendly(Gambit)
ImperiumUltraSemptor:setFriendly(Gambit)
ImperiumTriticum:setFriendly(Gambit)
ImperiumMerinita:setFriendly(Gambit)
ImperiumJuno:setFriendly(Gambit)
ImperiumPurusca:setFriendly(Gambit)
ImperiumAcadia:setFriendly(Gambit)
ImperiumAgmenos:setFriendly(Gambit)
ImperiumMisthos:setFriendly(Gambit)
Marine:setFriendly(Gambit)
Mercanti:setFriendly(Gambit)
Mechanicus:setFriendly(Gambit)
Independant:setFriendly(Gambit)
Defiance:setFriendly(Gambit)

--Chaos--

Imperium:setEnemy(Chaos)
ImperiumTarkus:setEnemy(Chaos)
ImperiumGisperion:setEnemy(Chaos)
MechanicusFractarius:setEnemy(Chaos)
MechanicusLascarios:setEnemy(Chaos)
ImperiumUltraSemptor:setEnemy(Chaos)
ImperiumTriticum:setEnemy(Chaos)
ImperiumMerinita:setEnemy(Chaos)
ImperiumJuno:setEnemy(Chaos)
ImperiumPurusca:setEnemy(Chaos)
ImperiumAcadia:setEnemy(Chaos)
ImperiumAgmenos:setEnemy(Chaos)
ImperiumMisthos:setEnemy(Chaos)
Marine:setEnemy(Chaos)
Mercanti:setEnemy(Chaos)
Mechanicus:setEnemy(Chaos)
Independant:setEnemy(Chaos)
Defiance:setEnemy(Chaos)
Gambit:setEnemy(Chaos)
Federation:setEnemy(Chaos)
Eldar:setEnemy(Chaos)
Tau:setEnemy(Chaos)
Xenos:setEnemy(Chaos)

Chaos:setEnemy(Imperium)
Chaos:setEnemy(ImperiumTarkus)
Chaos:setEnemy(ImperiumGisperion)
Chaos:setEnemy(MechanicusFractarius)
Chaos:setEnemy(MechanicusLascarios)
Chaos:setEnemy(ImperiumUltraSemptor)
Chaos:setEnemy(ImperiumTriticum)
Chaos:setEnemy(ImperiumMerinita)
Chaos:setEnemy(ImperiumJuno)
Chaos:setEnemy(ImperiumPurusca)
Chaos:setEnemy(ImperiumAcadia)
Chaos:setEnemy(ImperiumAgmenos)
Chaos:setEnemy(ImperiumMisthos)
Chaos:setEnemy(Marine)
Chaos:setEnemy(Mercanti)
Chaos:setEnemy(Mechanicus)
Chaos:setEnemy(Independant)
Chaos:setEnemy(Defiance)
Chaos:setEnemy(Gambit)
Chaos:setEnemy(Federation)
Chaos:setEnemy(Eldar)
Chaos:setEnemy(Tau)
Chaos:setEnemy(Xenos)

--Xenos--

Imperium:setEnemy(Xenos)
ImperiumTarkus:setEnemy(Xenos)
ImperiumGisperion:setEnemy(Xenos)
MechanicusFractarius:setEnemy(Xenos)
MechanicusLascarios:setEnemy(Xenos)
ImperiumUltraSemptor:setEnemy(Xenos)
ImperiumTriticum:setEnemy(Xenos)
ImperiumMerinita:setEnemy(Xenos)
ImperiumJuno:setEnemy(Xenos)
ImperiumPurusca:setEnemy(Xenos)
ImperiumAcadia:setEnemy(Xenos)
ImperiumAgmenos:setEnemy(Xenos)
ImperiumMisthos:setEnemy(Xenos)
Marine:setEnemy(Xenos)
Mercanti:setEnemy(Xenos)
Mechanicus:setEnemy(Xenos)
Independant:setEnemy(Xenos)
Defiance:setEnemy(Xenos)
Gambit:setEnemy(Xenos)
Eldar:setEnemy(Xenos)
Tau:setEnemy(Xenos)

Imperium:setEnemy(Tau)
ImperiumTarkus:setEnemy(Tau)
ImperiumGisperion:setEnemy(Tau)
MechanicusFractarius:setEnemy(Tau)
MechanicusLascarios:setEnemy(Tau)
ImperiumUltraSemptor:setEnemy(Tau)
ImperiumTriticum:setEnemy(Tau)
ImperiumMerinita:setEnemy(Tau)
ImperiumJuno:setEnemy(Tau)
ImperiumPurusca:setEnemy(Tau)
ImperiumAcadia:setEnemy(Tau)
ImperiumAgmenos:setEnemy(Tau)
ImperiumMisthos:setEnemy(Tau)
Marine:setEnemy(Tau)
Mercanti:setEnemy(Tau)
Mechanicus:setEnemy(Tau)
Independant:setEnemy(Tau)
Defiance:setEnemy(Tau)
Gambit:setEnemy(Tau)
Eldar:setEnemy(Tau)
Xenos:setEnemy(Tau)

Imperium:setEnemy(Eldar)
ImperiumTarkus:setEnemy(Eldar)
ImperiumGisperion:setEnemy(Eldar)
MechanicusFractarius:setEnemy(Eldar)
MechanicusLascarios:setEnemy(Eldar)
ImperiumUltraSemptor:setEnemy(Eldar)
ImperiumTriticum:setEnemy(Eldar)
ImperiumMerinita:setEnemy(Eldar)
ImperiumJuno:setEnemy(Eldar)
ImperiumPurusca:setEnemy(Eldar)
ImperiumAcadia:setEnemy(Eldar)
ImperiumAgmenos:setEnemy(Eldar)
ImperiumMisthos:setEnemy(Eldar)
Marine:setEnemy(Eldar)
Mercanti:setEnemy(Eldar)
Mechanicus:setEnemy(Eldar)
Independant:setEnemy(Eldar)
Defiance:setEnemy(Eldar)
Gambit:setEnemy(Eldar)
Tau:setEnemy(Eldar)
Xenos:setEnemy(Eldar)

--Fédération--

Federation:setEnemy(Imperium)
Federation:setEnemy(ImperiumTarkus)
Federation:setEnemy(ImperiumGisperion)
Federation:setEnemy(MechanicusFractarius)
Federation:setEnemy(MechanicusLascarios)
Federation:setEnemy(ImperiumUltraSemptor)
Federation:setEnemy(ImperiumTriticum)
Federation:setEnemy(ImperiumMerinita)
Federation:setEnemy(ImperiumJuno)
Federation:setEnemy(ImperiumPurusca)
Federation:setEnemy(ImperiumAcadia)
Federation:setEnemy(ImperiumAgmenos)
Federation:setEnemy(ImperiumMisthos)
Federation:setEnemy(Marine)
Federation:setEnemy(Mercanti)
Federation:setEnemy(Mechanicus)
Federation:setEnemy(Independant)
Federation:setEnemy(Defiance)
Federation:setEnemy(Gambit)